### PR TITLE
Service recovery fixed - 4th "no action" action removed #404

### LINKED ISSUE #404: Topshelf halts service recovery after third attempt
I am using Topshelf to create a Windows Service. This service will attempt recovery the first 3 failures, but after that, it no longer works.

Inspecting the service in Services on the host reveals:

    First Failure:          Restart the Service
    Second Failure:         Restart the Service
    Subsequent Failures:    Restart the Service
    Reset fail count after: 1 days
    Restart service after:  2 minutes

The service recovery code looks like this:

    f.EnableServiceRecovery(r =>
    {
        r.RestartService(2);
        r.RestartService(5);
        r.RestartService(5);
        r.OnCrashOnly();
        r.SetResetPeriod(1);
    });

Inspecting the Event Log shows the following messages after failed recovery:

    The MyService service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 120000 milliseconds: Restart the service.
    The MyService service terminated unexpectedly.  It has done this 2 time(s).  The following corrective action will be taken in 300000 milliseconds: Restart the service.
    The MyService service terminated unexpectedly.  It has done this 3 time(s).  The following corrective action will be taken in 300000 milliseconds: Restart the service.
    The MyService service terminated unexpectedly.  It has done this 4 time(s).

As is evident from the above, the fourth time does not trigger recovery.

Is this a Windows error, a Topshelf issue, or is there something wrong in my configuration?

### PR DESCRIPTION
**Pull request by maxcherednik**
Fixes #404

Pr was tested manually.
Now the configuration like this:
```C#
HostFactory.New(x =>
{
    x.EnableServiceRecovery(r =>
    {
        r.RestartService(0);
        r.RestartService(0);
        r.RestartService(0);
        //number of days until the error count resets
        r.SetResetPeriod(1);
    });
});
```

Works as Windows understands it:
First failure - restart
Second failure - restart
**Subsequent** failures - restart

Failure counter will be reset after 1 day, which means that during the first failure, the first action kicks in.

Ps.
If someone tries to register more than 3(Windows does not understand more than 3) actions, it will throw TopshelException.

### CODE REVIEW

File: src/Topshelf/Runtime/Windows/ServiceRecoveryOptions.cs [hunk 1]
```diff
@@ -34,6 +34,12 @@ public IEnumerable<ServiceRecoveryAction> Actions
 
         public void AddAction(ServiceRecoveryAction serviceRecoveryAction)
         {
+            if (_actions.Count == 3)
+            {
+                throw new TopshelfException("Recovery action can not be added. " +
+                                            "Windows recovery does not support more than 3 actions");
+            }
+
```
Comment (maxcherednik) [inline src/Topshelf/Runtime/Windows/ServiceRecoveryOptions.cs]: Here we can explicitly limit number of actions.

File: src/Topshelf/Runtime/Windows/WindowsServiceRecoveryController.cs [hunk 2]
```diff
@@ -57,12 +57,6 @@ public void SetServiceRecoveryOptions(HostSettings settings, ServiceRecoveryOpti
                     nextAction = (IntPtr)(nextAction.ToInt64() + actionSize);
                 }
 
-                var finalAction = new NativeMethods.SC_ACTION();
-                finalAction.Type = (int)NativeMethods.SC_ACTION_TYPE.None;
-                finalAction.Delay = (int)TimeSpan.FromMinutes(1).TotalMilliseconds;
-
-                Marshal.StructureToPtr(finalAction, nextAction, false);
-
```
Comment (maxcherednik) [inline src/Topshelf/Runtime/Windows/WindowsServiceRecoveryController.cs]: Why it was here in the first place? Seems like no need for this.

File: src/Topshelf/Runtime/Windows/WindowsServiceRecoveryController.cs [hunk 3]
```diff
@@ -77,7 +71,7 @@ public void SetServiceRecoveryOptions(HostSettings settings, ServiceRecoveryOpti
                     (int)TimeSpan.FromDays(options.ResetPeriod).TotalSeconds;
                 failureActions.lpRebootMsg = rebootMessage;
                 failureActions.lpCommand = runProgramCommand;
-                failureActions.cActions = actions.Count + 1;
+                failureActions.cActions = actions.Count;
```
Comment (maxcherednik) [inline src/Topshelf/Runtime/Windows/WindowsServiceRecoveryController.cs]: I hope I correctly counted the actions :)

**Comment by phatboyg** [comment]
You'll need to retarget your PR for the develop branch, or it won't be possible to merge it.

**Comment by phatboyg** [comment]
I don’t accept patches to master. Ever. The next release will have all the fixes.

**Comment by maxcherednik** [comment]
@phatboyg Retargeted to develop

File: src/Topshelf/Runtime/Windows/ServiceRecoveryOptions.cs (hunk 1 above)
Comment (zerg960) [reply src/Topshelf/Runtime/Windows/ServiceRecoveryOptions.cs:39]: FYI: Windows supports more than 3 actions when configured directly with sc.exe:
`sc failure SERVICE actions=restart/1000/restart/2000/restart/5000/restart/10000/restart/30000/restart/60000/restart/300000/reboot/300000/reboot/1800000/reboot/7200000`
Tested in Windows Server 2016 and Windows 11.
