### PR TITLE
ExitCode cast fix #477

### LINKED ISSUE #477: WindowsServiceHost.Run() throws an exception when returning
`WindowsServiceHost.Run()` returns a `TopshelfExitCode` by parsing `ServiceBase.ExitCode` as an enum, however 9 days ago `TopshelfExitCode` was changed to be a **struct** instead of an enum. This causes an exception to be thrown when `WindowsServiceHost.Run()` returns:

```
[2018-10-01 07:57:28.677 Error] [] The service terminated abnormally
System.ArgumentException: Type provided must be an Enum.
Parameter name: enumType
   at System.Enum.ToObject(Type enumType, Int32 value)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)
```

Bug was introduced here: https://github.com/Topshelf/Topshelf/commit/d47f7a17312a7d35ce012eb10b3c0c7039914f67#diff-d21b3cd5c675ec89e50e60b77e005c42

For now a workaround is to use 4.1.0 stable.

### PR DESCRIPTION
**Pull request by maxcherednik**
Fixes #477
Follow up for #475

This bug was due to 2 reasons:
1. There is no easy way to write unit test for the WindowsServiceHost class, so I did not do it with the last commit. I tried it manually and there was no cast issue for me. Explained in point 2.
2. It appears that when running as a windows service the actual exit code is taken from the ServiceBase.Exit right after `ServiceBase.OnStop` method exits. Even though process is still running, the exit code which is returned from Main method does not matter anymore. See comment inline.

### CODE REVIEW

File: src/Topshelf/Runtime/Windows/WindowsServiceHost.cs [hunk 1]
```diff
@@ -77,7 +77,12 @@ public TopshelfExitCode Run()
 
             Run(this);
 
-            return (TopshelfExitCode) Enum.ToObject(typeof(TopshelfExitCode), ExitCode);
+            // this error code does not matter when running as a windows service
+            // the actual exit code is taken from the ServiceBase.ExitCode
+            // Windows service tooling already sees the service as stopped here -
+            // once ServiceBase.OnStop method exits, but the process is not yet finished here.
+            // even if we put Thread.Sleep(600000) the process will be killed after some timeout
+            return new TopshelfExitCode(ExitCode);
```
Comment (maxcherednik) [inline src/Topshelf/Runtime/Windows/WindowsServiceHost.cs]: ❗️ The behaviour here is really tricky!
